plugins {
    id 'fabric-loom' version '1.10.5'
}
version = mod_version
group = mod_group_id
base.archivesName = 'field-emitters-fabric-1.20.1'
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
repositories {
    maven { url = 'https://api.modrinth.com/maven' }
}
dependencies {
    minecraft 'com.mojang:minecraft:1.20.1'
    mappings loom.officialMojangMappings()
    modImplementation 'net.fabricmc:fabric-loader:0.19.5'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.92.12+1.20.1'
    include modApi('teamreborn:energy:3.0.0')
    modImplementation 'maven.modrinth:forge-config-api-port:HvR3IdRE'
    // Loom does not put dependency jar-in-jar libraries on the development classpath.
    runtimeOnly 'com.electronwill.night-config:core:3.6.5'
    runtimeOnly 'com.electronwill.night-config:toml:3.6.5'
}
sourceSets.main.resources.srcDir 'src/generated/resources'

loom { runs { client { client() }; server { server(); programArg '--nogui' } } }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 17 }
tasks.withType(AbstractArchiveTask).configureEach { preserveFileTimestamps = false; reproducibleFileOrder = true }
processResources { inputs.property 'version', project.version; filesMatching('fabric.mod.json') { expand version: project.version } }
jar { includeEmptyDirs = false; exclude '.cache/**'; from('LICENSE') { into 'META-INF' } }
