org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.10
forge_version_range=[47.4.10,48)
loader_version_range=[47,)

mod_id=fieldemitters
mod_name=Field Emitters
mod_archive_name=field-emitters-forge-1.20.1
mod_license=Field Emitters License 1.0
mod_version=1.0.1
mod_group_id=com.zerotheabsolute.fieldemitters
mod_authors=ZeroTheAbsolute
mod_homepage=https://github.com/shikyo13/Field-Emitters
mod_issue_tracker=https://github.com/shikyo13/Field-Emitters/issues
mod_description=Terrain-following forcefields with entity filters, detection output and a handheld Field Tuner.
